apiVersion: operator.openshift.io/v1
kind: IngressController
metadata:
  name: custom
  namespace: openshift-ingress-operator
spec:
  domain: poc.ocpmas.snomas.gateterminal.com
  defaultCertificate:
    name: router-ca
  nodePlacement:
    nodeSelector:
      matchLabels:
        node-role.kubernetes.io/worker: ""
  defaultCertificate:
    name: router-certs-default
  endpointPublishingStrategy:
    type: HostNetwork
  httpEmptyRequestsPolicy: Respond
  httpErrorCodePages:
    name: ""
  replicas: 1
